### ISSUE TITLE
Pesquisar sobre as ferramentas de teste.

### ISSUE THREAD

**Issue by itmoura** [S204-Inatel-2022-1/web.idrugs.com#3]
Ferramenta que será usada para teste no frontend (React)

**Comment by Lucas-Alipio** [comment]
Para o Frontend será usado a ferramenta de testes [Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress). Ela possui uma estrutura amigável na construção das features.
Simples Exemplo:
![image](https://miro.medium.com/max/1400/1*c_fvqZuQX19HlpZByG9ulQ.jpeg)
Mais informações sobre [Cypress coverage for apps using create-react-app](https://www.cypress.io/blog/2019/09/05/cypress-code-coverage-for-create-react-app-v3/).
